[project]
name = "pysample"
version = "0.1.2"
description = "生成软件著作权文档的 python 工具"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.4",
    "pathspec>=1.1",
    "loguru>=0.7",
    "python-docx>=1.2",
]
authors = [{name = "Xiaoyu Guo", email = "biggates2010@gmail.com"}]
license = "MIT"

[project.scripts]
pysample = "main:main"

[project.urls]
Homepage = "https://github.com/EaphoneTech/pysample"

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.ruff.lint]
ignore = ["F821", "E501"]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
    "NPY",  # numpy specific rules
    "PERF", # "perflint"
    "RUF",  # ruff specific rules
]
