[project]
name = "pysample"
version = "1.0.0"
description = "生成软件著作权文档的 python 工具"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pathspec>=1.1",
    "typer>=0.16",
    "copyright-code-extractor>=0.2.1",
]
authors = [{name = "Xiaoyu Guo", email = "biggates2010@gmail.com"}]
license = "MIT"
license-files = ["licenses/*"]

[project.scripts]
pysample = "main:app"

[project.urls]
Homepage = "https://github.com/EaphoneTech/pysample"

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.ruff.lint]
ignore = ["F821", "E501", "RUF001", "RUF002", "RUF003"]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
    "PERF", # "perflint"
    "RUF",  # ruff specific rules
]

[dependency-groups]
dev = [
    "ruff>=0.15.21",
]
